version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      target: development
    working_dir: /app
    volumes:
      - ./:/app

  nginx:
    depends_on:
      - php
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8120:8120
